routes/admin.php
<?php
	Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.', 'middleware' => 'auth.admin'], function() {

		Route::get('/', 'Dashboard\DashboardController@index')->name('index');

		Route::group(['prefix' => 'profile', 'as' => 'profile.'], function() {
			Route::get('edit/{user}', 'Profile\ProfileController@edit')->name('edit');
			Route::post('edit/{user}', 'Profile\ProfileController@update')->name('update');
		});

		Route::group(['prefix' => 'projects', 'as' => 'project.'], function() {
			Route::group(['namespace' => 'Project'], function() {
				Route::get('/', 'ClientProjects@index')->name('index');
				Route::get('create', 'ClientProjects@create')->name('create');
				Route::post('create', 'ClientProjects@store')->name('store');
				Route::get('edit/{project}', 'ClientProjects@edit')->name('edit');
				Route::put('edit/{project}', 'ClientProjects@update')->name('update');
				Route::get('delete/{project}', 'ClientProjects@destroy')->name('destroy');
			});
			Route::group(['prefix' => '{project}/clients', 'as' => 'client.'], function() {
				Route::get('/', 'Client\ClientsController@index')->name('index');
				Route::get('create', 'Client\ClientsController@create')->name('create');
				Route::post('create', 'Client\ClientsController@store')->name('store');
				Route::get('{client}/edit', 'Client\ClientsController@edit')->name('edit');
				Route::post('{client}/edit', 'Client\ClientsController@update')->name('update');
				Route::get('{client}/delete', 'Client\ClientsController@destroy')->name('destroy');

				Route::group(['prefix' => '{client}/senderids', 'as' => 'senderids.'], function() {
					Route::group(['namespace' => 'SenderIds'], function() {
						Route::get('/', 'SenderIdsController@index')->name('index');
						Route::get('create', 'SenderIdsController@create')->name('create');
						Route::post('create', 'SenderIdsController@store')->name('store');
						Route::get('edit/{senderids}', 'SenderIdsController@edit')->name('edit');
						Route::put('edit/{senderids}', 'SenderIdsController@update')->name('update');
						Route::get('delete/{senderids}', 'SenderIdsController@destroy')->name('destroy');
					});
				});

				Route::group(['prefix' => '{client}/users', 'as' => 'users.'], function() {
					Route::get('/', 'Client\ClientUsersController@index')->name('index');
					Route::get('create', 'Client\ClientUsersController@create')->name('create');
					Route::get('edit/{user}', 'Client\ClientUsersController@edit')->name('edit');
					Route::post('create', 'Client\ClientUsersController@store')->name('store');
					Route::put('edit/{user}', 'Client\ClientUsersController@update')->name('update');
					Route::get('delete/{user}', 'Client\ClientUsersController@destroy')->name('destroy');
				});

				Route::group(['prefix' => '{client}/sub-account/','as' => 'sub.'], function () {
					Route::get('/', 'SubAccount\SubAccountsController@index')->name('index');
					Route::get('create', 'SubAccount\SubAccountsController@create')->name('create');
					Route::post('create', 'SubAccount\SubAccountsController@store')->name('store');
					Route::get('{subaccount}/settings', 'SubAccount\SubAccountsController@settings')->name('settings');
					Route::put('{subaccount}/settings', 'SubAccount\SubAccountsController@updateSettings')->name('settings');
					Route::get('{subaccount}/edit','SubAccount\SubAccountsController@edit')->name('edit');
					Route::put('{subaccount}/edit', 'SubAccount\SubAccountsController@update')->name('update');
					Route::get('{subaccount}/delete', 'SubAccount\SubAccountsController@delete')->name('delete');

					Route::group(['prefix' => '{subaccount}/campaigns/','as' => 'camp.'], function () {
						Route::group(['namespace' => 'Campaign'], function () {
							Route::get('/', 'CampaignController@index')->name('index');
							Route::get('create', 'CampaignController@create')->name('create');
							Route::post('create', 'CampaignController@store')->name('store');
							Route::get('{campaign}/edit','CampaignController@edit')->name('edit');
							Route::put('{campaign}/edit', 'CampaignController@update')->name('update');
							Route::get('{campaign}/delete', 'CampaignController@delete')->name('delete');
						});
					});

					Route::group(['prefix' => '{subAccount}/tasks/', 'namespace' => 'Task', 'as' => 'task.'], function() {
						// Route::get('/', 'ClientTasks@index')->name('index');
						// Route::get('create', 'ClientTasks@create')->name('create');
						// Route::post('create', 'ClientTasks@store')->name('store');
						// Route::get('{taskid}/edit','ClientTasks@edit')->name('edit');
						// Route::put('{taskid}/edit', 'ClientTasks@update')->name('update');
						// Route::get('{taskid}/delete', 'ClientTasks@destroy')->name('delete');

						Route::group(['prefix' => 'ots', 'namespace' => 'OneTimeSend', 'as' => 'ots.'], function() {
							Route::get('/', 'OneTimeSendController@index')->name('index');
							Route::get('create', 'OneTimeSendController@create')->name('create');
							Route::post('create', 'OneTimeSendController@store')->name('store');
							Route::get('{task}/edit','OneTimeSendController@edit')->name('edit');
							Route::put('{task}/edit', 'OneTimeSendController@update')->name('update');
							Route::get('{task}/delete', 'OneTimeSendController@destroy')->name('delete');

							Route::post('create/ajaxGenerateRecepient', 'OneTimeSendController@ajaxGenerateRecepient'); // ajax request generate recepient //
							Route::post('create/ajaxviewrecipient','OneTimeSendController@ajaxviewRecipient'); // view all recipients
							Route::post('create/ajaxCreateCampaign','OneTimeSendController@ajaxCreateCampaign'); // create  quick campaign
							Route::post('{task}/edit/ajaxCreateCampaign','OneTimeSendController@ajaxCreateCampaign'); // create  quick campaign
						});

						Route::group(['prefix' => 'tbs', 'namespace' => 'TextBlastSend', 'as' => 'tbs.'], function() {
							Route::get('/', 'TextBlastSendController@index')->name('index');
							Route::get('create', 'TextBlastSendController@create')->name('create');
							Route::post('create', 'TextBlastSendController@store')->name('store');
							Route::get('{task}/edit','TextBlastSendController@edit')->name('edit');
							Route::get('{task}/view','TextBlastSendController@view')->name('view');
							Route::put('{task}/view','TextBlastSendController@updateFormView')->name('update');
							Route::put('{task}/edit', 'TextBlastSendController@update')->name('update');
							Route::get('{task}/delete', 'TextBlastSendController@destroy')->name('delete');

							Route::post('create/ajaxGenerateRecipient', 'TextBlastSendController@ajaxGenerateRecepient'); // ajax request generate recepient //
							Route::post('create/ajaxViewRecipient','TextBlastSendController@ajaxViewRecipient'); // view all recipients
							Route::post('create/ajaxCreateCampaign','TextBlastSendController@ajaxCreateCampaign'); // create  quick campaign
							Route::post('{task}/edit/ajaxCreateCampaign','TextBlastSendController@ajaxCreateCampaign'); // create  quick campaign
							Route::post('{task}/edit/ajaxGenerateRecipient', 'TextBlastSendController@ajaxGenerateRecepient'); // ajax request generate recepient //
							Route::post('{task}/edit/ajaxViewRecipient','TextBlastSendController@ajaxviewRecipient'); // view all recipients
						});

						Route::group(['prefix' => 'it', 'namespace' => 'ImmediateTask', 'as' => 'it.'], function() {
							Route::get('/', 'ImmediateTaskController@index')->name('index');
							Route::get('create', 'ImmediateTaskController@create')->name('create');
							Route::post('create', 'ImmediateTaskController@store')->name('store');
							Route::get('{task}/edit','ImmediateTaskController@edit')->name('edit');
							Route::put('{task}/edit', 'ImmediateTaskController@update')->name('update');
							Route::get('{task}/delete', 'ImmediateTaskController@destroy')->name('delete');
						});
					});
				});

				Route::group(['prefix' => '{client}/gateway/','as' => 'api.'], function () {
					Route::group(['namespace' => 'ApiKey'], function () {
						Route::get('/', 'ApiKeyController@index')->name('index');
						Route::get('create', 'ApiKeyController@create')->name('create');
						Route::post('create', 'ApiKeyController@store')->name('store');
						Route::get('{apikey}/edit','ApiKeyController@edit')->name('edit');
						Route::put('{apikey}/edit', 'ApiKeyController@update')->name('update');
						Route::get('{apikey}/delete', 'ApiKeyController@delete')->name('delete');
					});
				});

				Route::group(['prefix' => '{client}/roles/','as' => 'role.'], function () {
					Route::get('/', 'Role\ClientRolesController@index')->name('index');
					Route::get('create', 'Role\ClientRolesController@create')->name('create');
					Route::post('create', 'Role\ClientRolesController@store')->name('store');
					Route::get('{role}/edit','Role\ClientRolesController@edit')->name('edit');
					Route::put('{role}/edit', 'Role\ClientRolesController@update')->name('update');
					Route::get('{role}/delete', 'Role\ClientRolesController@destroy')->name('delete');
				});

				Route::group(['prefix' => '{client}/customer-groups/','as' => 'customer-group.'], function () {
					Route::get('/', 'CustomerGroup\ClientCustomerGroupController@index')->name('index');
					Route::get('create', 'CustomerGroup\ClientCustomerGroupController@create')->name('create');
					Route::post('create', 'CustomerGroup\ClientCustomerGroupController@store')->name('store');
					Route::get('{customergroup}/edit','CustomerGroup\ClientCustomerGroupController@edit')->name('edit');
					Route::put('{customergroup}/edit', 'CustomerGroup\ClientCustomerGroupController@update')->name('update');
					Route::get('{customergroup}/delete', 'CustomerGroup\ClientCustomerGroupController@destroy')->name('delete');
				});

				Route::group(['prefix' => '{client}/customers/','as' => 'customer.'], function () {

routes/web.php
<?php

use ATM\Repositories\Sms\SmsFacade;
use Illuminate\Support\Facades\DB;
use ATM\Repositories\Tasks\JobsTodaySend\JobToday;
use ATM\Repositories\Tasks\JobsTomorrow\JobTomorrow;
use ATM\Repositories\Tasks\JobsNextMonth\JobNextMonth;
use ATM\Repositories\Tasks\Jobs15thDayToEndMonth\Job15thDayToEndMonth;
use ATM\Repositories\Tasks\JobsAfterTomorrowTo14thDay\JobAfterTomorrowTo14thDay;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('manual-run-sched/638gfhdfg-s0f7sd85f0f9hadf4as5fs7g32364', function () {
   event(new \App\Events\CronJobsTomorrow(today()));
   echo 'done';
});

Route::get('get-php-info', function() {
	phpinfo();
	die;
});

Route::get('beechoo-smart-globe-customers', function() {
	$customers = ATM\Repositories\Customers\Customer::where('client_id', 70)->get();
	$invalidPrefixes = invalidNumberPrefixes();

	$filteredSmart = $customers->filter(function($cust) {
		$sanitized = str_replace('+', '', $cust->mobile);
		$numPrefix = substr($sanitized, 0, 5);

		return in_array($numPrefix, ['63985', '63982', '63980', '63969', '63968', '63960', '63959', '63958', '63957', '63971', '63963', '63981', '63970', '63961', '63973', '63950', '63951', '63914', '63913', '63911', '63900', '63940', '63813', '63907', '63908', '63909', '63910', '63918', '63912', '63919', '63920', '63921', '63928', '63929', '63930', '63938', '63939', '63946', '63947', '63948', '63949', '63989', '63998', '63999']);
	})->values();

	$filteredSun = $customers->filter(function($cust) use ($invalidPrefixes) {
		$sanitized = str_replace('+', '', $cust->mobile);
		$numPrefix = substr($sanitized, 0, 5);

		return in_array($numPrefix, ['63972', '63962', '63952', '63974', '63984', '63944', '63941', '63931', '63924', '63922', '63923', '63925', '63932', '63933', '63942', '63934', '63943']);
	})->values();

	$filteredDito = $customers->filter(function($cust) use ($invalidPrefixes) {
		$sanitized = str_replace('+', '', $cust->mobile);
		$numPrefix = substr($sanitized, 0, 5);

		return in_array($numPrefix, ['63898', '63897', '63896', '63895', '63993', '63991', '63992', '63994']);
	})->values();

	$filteredGlobe = $customers->filter(function($cust) use ($invalidPrefixes) {
		$sanitized = str_replace('+', '', $cust->mobile);
		$numPrefix = substr($sanitized, 0, 5);

		return !in_array($numPrefix, $invalidPrefixes);
	})->values();

	dd('SMART', $filteredSmart, 'SUN', $filteredSun, 'DITO', $filteredDito, 'GLOBE', $filteredGlobe);
});

Auth::routes();

Route::get('/logout', 'Auth\LoginController@logout');
Route::get('/', 'Auth\LoginController@manageRedirect');

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'asset-page'], function() {
	Route::get('/assets', function () {
		return view('asset_pages.asset_page');
	})->name('assetPage');
	Route::get('/two-column', function () {
		return view('asset_pages.two_columns');
	})->name('twoColumnPage');
	Route::get('/index-page', function () {
		return view('asset_pages.index_page');
	})->name('indexPage');
});

// Route::get('api/immediate-sm', 'Api\Task\ImmediateTaskController@createJob')->name('it.create.job');

Route::get('{subaccountUuid}/{beforeUuid}/change-context', 'SubAccount\ContextController@changeContext')->name('sub.context.change');

Route::get('move-smart-numbers-to-failed', function() {

	try {
		DB::beginTransaction();

		$smartNumberClients = [70]; // beechoo
		$invalidPrefixes = invalidNumberPrefixes();
	
		$jobs15thDayToEndMonth = Job15thDayToEndMonth::whereIn('client_id', $smartNumberClients)->get();
		$jobsAfterTomorrowTo14thDay = JobAfterTomorrowTo14thDay::whereIn('client_id', $smartNumberClients)->get();
		$jobsNextMonth = JobNextMonth::whereIn('client_id', $smartNumberClients)->get();
		$jobsTodaySend = JobToday::whereIn('client_id', $smartNumberClients)->get();
		$jobsTomorrow = JobTomorrow::whereIn('client_id', $smartNumberClients)->get();
	
		$smsFacade = resolve(\ATM\Repositories\Sms\SmsFacade::class);
	
		if ($jobs15thDayToEndMonth->count() > 0) {
			foreach($jobs15thDayToEndMonth as $job15thDayToEndMonth) {
				if ($job15thDayToEndMonth && $job15thDayToEndMonth->customer_number) {
					$jobNumPrefix = substr($job15thDayToEndMonth->customer_number, 0, 5);
		
					if (in_array($jobNumPrefix, $invalidPrefixes)) {
						$smsFacade->forceFailJobs($job15thDayToEndMonth, true, 'Smart/Sun/DITO Number', explode(",", $job15thDayToEndMonth->id));
					}
				}
			}
		}
	
		if ($jobsAfterTomorrowTo14thDay->count() > 0) {
			foreach($jobsAfterTomorrowTo14thDay as $jobAfterTomorrowTo14thDay) {
				if ($jobAfterTomorrowTo14thDay && $jobAfterTomorrowTo14thDay->customer_number) {
					$jobNumPrefix = substr($jobAfterTomorrowTo14thDay->customer_number, 0, 5);
		
					if (in_array($jobNumPrefix, $invalidPrefixes)) {
						$smsFacade->forceFailJobs($jobAfterTomorrowTo14thDay, true, 'Smart/Sun/DITO Number', explode(",", $jobAfterTomorrowTo14thDay->id));
					}
				}
			}
		}
	
		if ($jobsNextMonth->count() > 0) {
			foreach($jobsNextMonth as $jobNextMonth) {
				if ($jobNextMonth && $jobNextMonth->customer_number) {
					$jobNumPrefix = substr($jobNextMonth->customer_number, 0, 5);
					
					if (in_array($jobNumPrefix, $invalidPrefixes)) {
						$smsFacade->forceFailJobs($jobNextMonth, true, 'Smart/Sun/DITO Number', explode(",", $jobNextMonth->id));
					}
				}
			}
		}
	
		if ($jobsTodaySend->count() > 0) {
			foreach($jobsTodaySend as $jobToday) {
				if ($jobToday && $jobToday->customer_number) {
					$jobNumPrefix = substr($jobToday->customer_number, 0, 5);
		
					if (in_array($jobNumPrefix, $invalidPrefixes)) {
						$smsFacade->forceFailJobs($jobToday, true, 'Smart/Sun/DITO Number', explode(",", $jobToday->id));
					}
				}
			}
		}
	
		if ($jobsTomorrow->count() > 0) {
			foreach($jobsTomorrow as $jobTomorrow) {
				if ($jobTomorrow && $jobTomorrow->customer_number) {
					$jobNumPrefix = substr($jobTomorrow->customer_number, 0, 5);
		
					if (in_array($jobNumPrefix, $invalidPrefixes)) {
						$smsFacade->forceFailJobs($jobTomorrow, true, 'Smart/Sun/DITO Number', explode(",", $jobTomorrow->id));
					}
				}
			}
		}
		
		DB::commit();
		return 'sms failed successully !';
	} catch (\Exception $e) {
		DB::rollBack();
		
		dd($e->getErrors());
	}

});
/**
 * -----------------------------------------------------------
 * Sub Account Routes
 * -----------------------------------------------------------
 */

require base_path('routes/subaccount.php');

/**
 * -----------------------------------------------------------
 * Client Routes
 * -----------------------------------------------------------
 */

require base_path('routes/client.php');

/**
 * -----------------------------------------------------------
 * Admin Routes
 * -----------------------------------------------------------
 */

require base_path('routes/admin.php');

/**
 * -----------------------------------------------------------
 * WEB API's
 * -----------------------------------------------------------
 */

require base_path('routes/web-api.php');

resources/views/admin/clients/create.blade.php
@extends('layouts.fixed_header_admin')

{{-- Page title --}}
@section('title')
    {{ $title ?: 'Title goes here' }}
    @parent
@stop

{{-- Page Breadcrumbs --}}
@section('crumbs')
    <li class="breadcrumb-item">
        <a href="{{ route('admin.project.index') }}">Projects</a>
    </li>
    <li class="breadcrumb-item">
        <a href="{{ route('admin.project.client.index',[$project]) }}">Clients</a>
    </li>
    <li class="active breadcrumb-item">Add Clients</li>
@stop

{{-- Page content --}}
@section('content')

    <div class="card m-b-10">
        <div class="card-body">
            <div class="row">
                <div class="col">
                    <h3 class="m-b-0">
                        {{ isset($title) ? $title : 'Page Header Title' }}
                    </h3>
                </div>
            </div>
        </div>
    </div>

    @include('templates.clients.form', [
        'client' => new \ATM\Repositories\Client\Client,
        'method' => 'post',
    ])

@stop

resources/views/admin/clients/edit.blade.php
@extends('layouts.fixed_header_admin')

{{-- Page title --}}
@section('title')
    {{ $title ?: 'Title goes here' }}
    @parent
@stop

{{-- Page Breadcrumbs --}}
@section('crumbs')
    <li class="breadcrumb-item">
        <a href="{{ route('admin.project.index') }}">Projects</a>
    </li>
    <li class="breadcrumb-item">
        <a href="{{ route('admin.project.client.index',[$project]) }}">Clients</a>
    </li>
    <li class="active breadcrumb-item">Edit Client - {{ ucwords($client->company_name) }}</li>
@stop

{{-- Page content --}}
@section('content')

    <div class="card m-b-10">
        <div class="card-body">
            <div class="row">
                <div class="col">
                    <h3 class="m-b-0">
                        {{ isset($title) ? $title : 'Page Header Title' }}
                    </h3>
                </div>
                {{-- <div class="col">
                    <div class="btn-group float-right">
                        <a href="{{ route('admin.user.create') }}" class=" btn btn-success m-r-5">
                            Add Entity  <i class="fa fa-plus"></i>
                        </a>
                        <a href="{{ route('admin.user.create') }}" class=" btn btn-primary">
                            Print  <i class="fa fa-print"></i>
                        </a>
                    </div>
                </div> --}}
            </div>
        </div>
    </div>

    @include('templates.clients.form', [
        'client' => $client,
        'method' => 'POST',
    ])

@stop

resources/views/admin/clients/index.blade.php
@extends('layouts.fixed_header_admin')

{{-- Page title --}}
@section('title')
    {{ isset($title) ? $title : '' }}
    @parent
@stop

{{-- Page Breadcrumbs --}}
@section('crumbs')
    <li class="breadcrumb-item">
        <a href="{{ route('admin.project.index') }}">Projects</a>
    </li>
    <li class="active breadcrumb-item">Clients</li>
@stop

{{-- Page content --}}
@section('content')
    <div class="card m-b-10">
        <div class="card-body">
            <div class="row">
                <div class="col">
                    <h3 class="m-b-0">
                        {{ isset($title) ? strtoupper($project->name)."'s ".$title : 'Page Header Title' }}
                    </h3>
                </div>
                <div class="col">
                    <div class="btn-group float-right">
                        <a href="{{ route('admin.project.client.create', $project) }}" class=" btn btn-success m-r-5">
                            Add Client&nbsp;&nbsp;<i class="fa fa-plus"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
  {{--   @include('partials.form-success') --}}
    {{-- @include('partials.filters') --}}

    <div class="card">
        <div class="card-body" id="client_body">
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover no-footer table_res datatable_with_expand_details table-data" id="datatable">
                    <thead>
                        <tr role="row">
                            <th class="sorting_asc" tabindex="0">#</th>
                            <th class="sorting_asc" tabindex="0">Logo</th>
                            <th class="sorting_asc" tabindex="0">Company Name</th>
                            <th class="sorting" tabindex="0">Client ID</th>
                            <th class="sorting d-none" tabindex="0">Contact Person</th>
                            <th class="sorting d-none" tabindex="0">Email</th>
                            <th class="sorting d-none" tabindex="0">Phone</th>
                            <th class="sorting" tabindex="0">Mobile</th>
                            <th class="sorting wid-10" data-orderable="false" tabindex="0">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($clients as $client)
                        <tr class="get-data">
                            <td>{{ $loop->iteration }}</td>
                            <td><img src="{{ asset($client->img_thumb_path) }}" alt="" style="max-width: 50px;"></td>
                            <td><a href="{{ route('admin.project.client.edit', [$project, $client]) }}" class="name-anchor">{{ $client->company_name }}</a><a href="javascript:;" class="textify-more-details">More Details</a></td>
                            <td>{{ $client->cuid }}</td>
                            <td class="d-none" data-more-details="true" data-more-details-head-title="Company Name">{{ $client->company_name }}</td>
                            <td class="d-none" data-more-details="true" data-more-details-head-title="Email">{{ $client->contact_email }}</td>
                            <td class="d-none" data-more-details="true" data-more-details-head-title="Phone">{{ $client->contact_telephone }}</td>
                            <td>{{ $client->contact_mobile }}</td>
                            <td>
                                <a href="{{ route('admin.project.client.edit', [$project, $client]) }}" title="Edit" class="btn btn-sm btn-info"
                                    data-toggle="tooltip" data-placement="top" title="">
                                    <i class="fa fa-pencil" aria-hidden="true"></i>
                                </a>
                                {{--<a href="{{ route('admin.project.client.api.index', [$project, $client ]) }}" title="Gateway Keys" class="btn btn-sm btn-info">Gateway Keys</a>--}}
                                <a href="{{ route('admin.project.client.sub.index', [$project, $client]) }}" title="Sub Accounts" class="btn btn-sm btn-info">Sub Accounts</a>
                                <a href="{{ route('admin.project.client.senderids.index', [$project, $client]) }}" title="Sub Accounts" class="btn btn-sm btn-info">Sender Ids</a>
                                <a href="{{ route('admin.project.client.role.index', [$project, $client]) }}" title="Role" class="btn btn-sm btn-info">Role</a>
                                <a href="{{ route('admin.project.client.users.index', [$project, $client]) }}" title="Users" class="btn btn-sm btn-info">Users</a>
                                <a href="{{ route('admin.project.client.customer.index', [$project, $client]) }}" title="Customer Group" class="btn btn-sm btn-info">Contacts</a>
                                <a href="{{ route('admin.project.client.destroy', [$project, $client]) }}" title="Delete" class="btn btn-sm btn-danger"><i class="fa fa-trash" aria-hidden="true"></i></a>
                            </td>
                        </tr>
                        @empty
                        <tr>
                            <td colspan="9">No records found!</td>
                        </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>
    </div>
    
    <!--<tr class="details">
        <td class="details" colspan="6">
            <ul>
                @if( $client->subaccounts->count() > 0 )
                    <li><span>Sub Accounts:</span>
                        <ul>
                            @foreach ($client->subaccounts as $item)
                                <li>
                                    <span><strong>{{ $item->account_name }}</strong></span>
                                    <span>Credits: {{ $item->credit->pending_balance }}</span>
                                    <span>Contacts: {{ $item->customers->count() }}</span>
                                </li>
                            @endforeach
                        </ul>
                    </li>
                @endif
                @if( $client->customers->count() )
                    <li><span>Total Contacts:</span> {{ $client->customers->count() }}</li>
                @endif
                @if( $client->company_name )
                    <li><span>Email:</span> {{ $client->company_name }}</li>
                @endif
                @if( $client->contact_email )
                    <li><span>Phone:</span> {{ $client->contact_email }}</li>
                @endif
                @if( $client->contact_telephone )
                    <li><span>Contact Person:</span> {{ $client->contact_telephone }}</li>
                @endif
            </ul>
        </td>
    </tr>-->
        <!-- /.inner -->
    <!-- /.outer -->
@stop
{{-- page level scripts --}}